# Generated by Django 3.0.4 on 2020-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
