# Generated by Django 3.0.4 on 2020-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BigIntegerField(),
        ),
    ]
