# Generated by Django 3.0.4 on 2020-11-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=344, null=True),
        ),
    ]
