# Generated by Django 3.0.4 on 2020-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rais', '0002_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=345, null=True),
        ),
    ]
