# Generated by Django 3.0.4 on 2020-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rais', '0003_auto_20201111_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
