# Generated by Django 3.0.4 on 2020-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rais', '0004_auto_20201111_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
